package com.droidb.com.droiddblibrary.database;

/**
 * Created by PrashantKumar on 5/15/17.
 */

public interface ISchema {
  String DROID_DB_TABLE_PREFERENCES = "DROID_DB_PREFERENCES";
  String DROID_DB_TABLE_PREFERENCES_KEY = "DROID_DB_KEY";
  String DROID_DB_TABLE_PREFERENCES_VALUE = "DROID_DB_VALUE";
  String CREATE_PREFERENCES_TABLE = "CREATE TABLE IF NOT EXISTS " + DROID_DB_TABLE_PREFERENCES
      + " (" + DROID_DB_TABLE_PREFERENCES_KEY + " TEXT PRIMARY KEY, "
      + DROID_DB_TABLE_PREFERENCES_VALUE + " TEXT" + ")";
}
